import React from 'react'
import {WithTranslation, withTranslation} from 'react-i18next'
import {worldCategories} from 'src/setup/SetupPage/Gallery/category'
import MapSelection from 'src/setup/SetupPage/Step/WorldSetup/MapSelection'
import Gallery from 'src/setup/SetupPage/Gallery'
import './style.scss'
import {Resource} from '@joystack/protocol/realm/resource'

interface State {
  world: Resource.AsObject | null
}

class WorldMenu extends React.Component<WithTranslation, State> {
  constructor(properties: any) {
    super(properties)
    this.state = {world: null}
  }

  render() {
    const {t} = this.props
    return (
      <div className="world-menu-content">
        <Gallery.Selection
          resource={this.state.world}
          onDeselect={() => this.clearSelection()}
          title={t('WORLD_MENU.DEFAULT_MAP')}
          subTitle={t('WORLD_MENU.AUTOGENERATED_MAP')}
        />
        <MapSelection/>
        <Gallery
          onSelect={resource => this.selectItem(resource)}
          title={t('WORLD_MENU.SELECT_FROM_GALLERY')}
          categories={worldCategories}
        />
      </div>
    )
  }

  private selectItem(resource: Resource.AsObject) {
    this.setState({world: resource})
  }

  private clearSelection() {
    this.setState({world: null,})
  }
}

export default withTranslation('dashboard')(WorldMenu)
